[package]
name = "gtkrest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.2.0", package = "libadwaita" }
gtk = { version = "0.5.1", package = "gtk4" }

[build-dependencies]
glib-build-tools = "0.16.0"
